### ISSUE TITLE
Update for 3.x?

### ISSUE THREAD

**Issue by ScriptPup** [microsoft/powerbi-visuals-utils-dataviewutils#30]
Using pbiviz 3.1.2, this utils package doesn't work using the steps provided. When importing using the direct path instead, <del>the getCategoryIndexOfRole fails to work correctly as it's looking for type DataViewCategoryColumn, but the dataview categorical sub-property is typed as DataViewCategorical... </del> turns out I was using the wrong property (needed to go down one more.) 
`this.dataView.categorical.categories` vs using categorical.

The import still fails using the provided steps though, so it'd be great to get any updated steps so I don't need to point to the node directory.

**Comment by helen508light** [comment]
Please see the https://github.com/microsoft/powerbi-visuals-gantt
There are the a example of usage with API 3.1.2 and the latest dataViewUtils
