### ISSUE TITLE
Module '"powerbi-visuals-utils-dataviewutils"' has no exported member 'dataViewWildcard'

### ISSUE THREAD

**Issue by krngd2** [microsoft/powerbi-visuals-utils-dataviewutils#47]
I am trying to implement [conditional formatting](https://docs.microsoft.com/en-us/power-bi/developer/visuals/conditional-format#define-how-conditional-formatting-behaves) in my custom visuals
 [this official documentation](https://docs.microsoft.com/en-us/power-bi/developer/visuals/utils-dataview#) imports `dataViewWildcard`  but there is not exported member in `powerbi-visuals-utils-dataviewutils`

**Comment by dynamicapps** [comment]
Are you using 2.4.0?  Looks like it was added then.

**Comment by krngd2** [comment]
Yeah, I upgraded and its working fine now. Thanks
